export interface FixtureSeed {
  match_number: number;
  stage: string;
  group_letter?: string;
  date?: string;
  venue: string;
  home_code?: string;
  away_code?: string;
  home_label: string;
  away_label: string;
}

const GROUP_FIXTURES: FixtureSeed[] = [
  { match_number: 1, stage: "group", group_letter: "A", date: "2026-06-11", venue: "Mexico City Stadium", home_code: "MEX", away_code: "RSA", home_label: "Mexico", away_label: "South Africa" },
  { match_number: 2, stage: "group", group_letter: "A", date: "2026-06-11", venue: "Estadio Guadalajara", home_code: "KOR", away_code: "CZE", home_label: "Korea Republic", away_label: "Czechia" },
  { match_number: 3, stage: "group", group_letter: "B", date: "2026-06-12", venue: "Toronto Stadium", home_code: "CAN", away_code: "BIH", home_label: "Canada", away_label: "Bosnia and Herzegovina" },
  { match_number: 4, stage: "group", group_letter: "D", date: "2026-06-12", venue: "Los Angeles Stadium", home_code: "USA", away_code: "PAR", home_label: "USA", away_label: "Paraguay" },
  { match_number: 5, stage: "group", group_letter: "C", date: "2026-06-13", venue: "Boston Stadium", home_code: "HAI", away_code: "SCO", home_label: "Haiti", away_label: "Scotland" },
  { match_number: 6, stage: "group", group_letter: "D", date: "2026-06-13", venue: "BC Place Vancouver", home_code: "AUS", away_code: "TUR", home_label: "Australia", away_label: "Türkiye" },
  { match_number: 7, stage: "group", group_letter: "C", date: "2026-06-13", venue: "New York New Jersey Stadium", home_code: "BRA", away_code: "MAR", home_label: "Brazil", away_label: "Morocco" },
  { match_number: 8, stage: "group", group_letter: "B", date: "2026-06-13", venue: "San Francisco Bay Area Stadium", home_code: "QAT", away_code: "SUI", home_label: "Qatar", away_label: "Switzerland" },
  { match_number: 9, stage: "group", group_letter: "E", date: "2026-06-14", venue: "Philadelphia Stadium", home_code: "CIV", away_code: "ECU", home_label: "Côte d'Ivoire", away_label: "Ecuador" },
  { match_number: 10, stage: "group", group_letter: "E", date: "2026-06-14", venue: "Houston Stadium", home_code: "GER", away_code: "CUW", home_label: "Germany", away_label: "Curaçao" },
  { match_number: 11, stage: "group", group_letter: "F", date: "2026-06-14", venue: "Dallas Stadium", home_code: "NED", away_code: "JPN", home_label: "Netherlands", away_label: "Japan" },
  { match_number: 12, stage: "group", group_letter: "F", date: "2026-06-14", venue: "Estadio Monterrey", home_code: "SWE", away_code: "TUN", home_label: "Sweden", away_label: "Tunisia" },
  { match_number: 13, stage: "group", group_letter: "H", date: "2026-06-15", venue: "Miami Stadium", home_code: "KSA", away_code: "URU", home_label: "Saudi Arabia", away_label: "Uruguay" },
  { match_number: 14, stage: "group", group_letter: "H", date: "2026-06-15", venue: "Atlanta Stadium", home_code: "ESP", away_code: "CPV", home_label: "Spain", away_label: "Cabo Verde" },
  { match_number: 15, stage: "group", group_letter: "G", date: "2026-06-15", venue: "Los Angeles Stadium", home_code: "IRN", away_code: "NZL", home_label: "IR Iran", away_label: "New Zealand" },
  { match_number: 16, stage: "group", group_letter: "G", date: "2026-06-15", venue: "Seattle Stadium", home_code: "BEL", away_code: "EGY", home_label: "Belgium", away_label: "Egypt" },
  { match_number: 17, stage: "group", group_letter: "I", date: "2026-06-16", venue: "New York New Jersey Stadium", home_code: "FRA", away_code: "SEN", home_label: "France", away_label: "Senegal" },
  { match_number: 18, stage: "group", group_letter: "I", date: "2026-06-16", venue: "Boston Stadium", home_code: "IRQ", away_code: "NOR", home_label: "Iraq", away_label: "Norway" },
  { match_number: 19, stage: "group", group_letter: "J", date: "2026-06-16", venue: "Kansas City Stadium", home_code: "ARG", away_code: "ALG", home_label: "Argentina", away_label: "Algeria" },
  { match_number: 20, stage: "group", group_letter: "J", date: "2026-06-16", venue: "San Francisco Bay Area Stadium", home_code: "AUT", away_code: "JOR", home_label: "Austria", away_label: "Jordan" },
  { match_number: 21, stage: "group", group_letter: "L", date: "2026-06-17", venue: "Toronto Stadium", home_code: "GHA", away_code: "PAN", home_label: "Ghana", away_label: "Panama" },
  { match_number: 22, stage: "group", group_letter: "L", date: "2026-06-17", venue: "Dallas Stadium", home_code: "ENG", away_code: "CRO", home_label: "England", away_label: "Croatia" },
  { match_number: 23, stage: "group", group_letter: "K", date: "2026-06-17", venue: "Houston Stadium", home_code: "POR", away_code: "COD", home_label: "Portugal", away_label: "Congo DR" },
  { match_number: 24, stage: "group", group_letter: "K", date: "2026-06-17", venue: "Mexico City Stadium", home_code: "UZB", away_code: "COL", home_label: "Uzbekistan", away_label: "Colombia" },
  { match_number: 25, stage: "group", group_letter: "A", date: "2026-06-18", venue: "Atlanta Stadium", home_code: "CZE", away_code: "RSA", home_label: "Czechia", away_label: "South Africa" },
  { match_number: 26, stage: "group", group_letter: "B", date: "2026-06-18", venue: "Los Angeles Stadium", home_code: "SUI", away_code: "BIH", home_label: "Switzerland", away_label: "Bosnia and Herzegovina" },
  { match_number: 27, stage: "group", group_letter: "B", date: "2026-06-18", venue: "BC Place Vancouver", home_code: "CAN", away_code: "QAT", home_label: "Canada", away_label: "Qatar" },
  { match_number: 28, stage: "group", group_letter: "A", date: "2026-06-18", venue: "Estadio Guadalajara", home_code: "MEX", away_code: "KOR", home_label: "Mexico", away_label: "Korea Republic" },
  { match_number: 29, stage: "group", group_letter: "C", date: "2026-06-19", venue: "Philadelphia Stadium", home_code: "BRA", away_code: "HAI", home_label: "Brazil", away_label: "Haiti" },
  { match_number: 30, stage: "group", group_letter: "C", date: "2026-06-19", venue: "Boston Stadium", home_code: "SCO", away_code: "MAR", home_label: "Scotland", away_label: "Morocco" },
  { match_number: 31, stage: "group", group_letter: "D", date: "2026-06-19", venue: "San Francisco Bay Area Stadium", home_code: "TUR", away_code: "PAR", home_label: "Türkiye", away_label: "Paraguay" },
  { match_number: 32, stage: "group", group_letter: "D", date: "2026-06-19", venue: "Seattle Stadium", home_code: "USA", away_code: "AUS", home_label: "USA", away_label: "Australia" },
  { match_number: 33, stage: "group", group_letter: "E", date: "2026-06-20", venue: "Toronto Stadium", home_code: "GER", away_code: "CIV", home_label: "Germany", away_label: "Côte d'Ivoire" },
  { match_number: 34, stage: "group", group_letter: "E", date: "2026-06-20", venue: "Kansas City Stadium", home_code: "ECU", away_code: "CUW", home_label: "Ecuador", away_label: "Curaçao" },
  { match_number: 35, stage: "group", group_letter: "F", date: "2026-06-20", venue: "Houston Stadium", home_code: "NED", away_code: "SWE", home_label: "Netherlands", away_label: "Sweden" },
  { match_number: 36, stage: "group", group_letter: "F", date: "2026-06-20", venue: "Estadio Monterrey", home_code: "TUN", away_code: "JPN", home_label: "Tunisia", away_label: "Japan" },
  { match_number: 37, stage: "group", group_letter: "H", date: "2026-06-21", venue: "Miami Stadium", home_code: "URU", away_code: "CPV", home_label: "Uruguay", away_label: "Cabo Verde" },
  { match_number: 38, stage: "group", group_letter: "H", date: "2026-06-21", venue: "Atlanta Stadium", home_code: "ESP", away_code: "KSA", home_label: "Spain", away_label: "Saudi Arabia" },
  { match_number: 39, stage: "group", group_letter: "G", date: "2026-06-21", venue: "Los Angeles Stadium", home_code: "BEL", away_code: "IRN", home_label: "Belgium", away_label: "IR Iran" },
  { match_number: 40, stage: "group", group_letter: "G", date: "2026-06-21", venue: "BC Place Vancouver", home_code: "NZL", away_code: "EGY", home_label: "New Zealand", away_label: "Egypt" },
  { match_number: 41, stage: "group", group_letter: "I", date: "2026-06-22", venue: "New York New Jersey Stadium", home_code: "NOR", away_code: "SEN", home_label: "Norway", away_label: "Senegal" },
  { match_number: 42, stage: "group", group_letter: "I", date: "2026-06-22", venue: "Philadelphia Stadium", home_code: "FRA", away_code: "IRQ", home_label: "France", away_label: "Iraq" },
  { match_number: 43, stage: "group", group_letter: "J", date: "2026-06-22", venue: "Dallas Stadium", home_code: "ARG", away_code: "AUT", home_label: "Argentina", away_label: "Austria" },
  { match_number: 44, stage: "group", group_letter: "J", date: "2026-06-22", venue: "San Francisco Bay Area Stadium", home_code: "JOR", away_code: "ALG", home_label: "Jordan", away_label: "Algeria" },
  { match_number: 45, stage: "group", group_letter: "L", date: "2026-06-23", venue: "Boston Stadium", home_code: "ENG", away_code: "GHA", home_label: "England", away_label: "Ghana" },
  { match_number: 46, stage: "group", group_letter: "L", date: "2026-06-23", venue: "Toronto Stadium", home_code: "PAN", away_code: "CRO", home_label: "Panama", away_label: "Croatia" },
  { match_number: 47, stage: "group", group_letter: "K", date: "2026-06-23", venue: "Houston Stadium", home_code: "POR", away_code: "UZB", home_label: "Portugal", away_label: "Uzbekistan" },
  { match_number: 48, stage: "group", group_letter: "K", date: "2026-06-23", venue: "Estadio Guadalajara", home_code: "COL", away_code: "COD", home_label: "Colombia", away_label: "Congo DR" },
  { match_number: 49, stage: "group", group_letter: "C", date: "2026-06-24", venue: "Miami Stadium", home_code: "SCO", away_code: "BRA", home_label: "Scotland", away_label: "Brazil" },
  { match_number: 50, stage: "group", group_letter: "C", date: "2026-06-24", venue: "Atlanta Stadium", home_code: "MAR", away_code: "HAI", home_label: "Morocco", away_label: "Haiti" },
  { match_number: 51, stage: "group", group_letter: "B", date: "2026-06-24", venue: "BC Place Vancouver", home_code: "SUI", away_code: "CAN", home_label: "Switzerland", away_label: "Canada" },
  { match_number: 52, stage: "group", group_letter: "B", date: "2026-06-24", venue: "Seattle Stadium", home_code: "BIH", away_code: "QAT", home_label: "Bosnia and Herzegovina", away_label: "Qatar" },
  { match_number: 53, stage: "group", group_letter: "A", date: "2026-06-24", venue: "Mexico City Stadium", home_code: "CZE", away_code: "MEX", home_label: "Czechia", away_label: "Mexico" },
  { match_number: 54, stage: "group", group_letter: "A", date: "2026-06-24", venue: "Estadio Monterrey", home_code: "RSA", away_code: "KOR", home_label: "South Africa", away_label: "Korea Republic" },
  { match_number: 55, stage: "group", group_letter: "E", date: "2026-06-25", venue: "Philadelphia Stadium", home_code: "CUW", away_code: "CIV", home_label: "Curaçao", away_label: "Côte d'Ivoire" },
  { match_number: 56, stage: "group", group_letter: "E", date: "2026-06-25", venue: "New York New Jersey Stadium", home_code: "ECU", away_code: "GER", home_label: "Ecuador", away_label: "Germany" },
  { match_number: 57, stage: "group", group_letter: "F", date: "2026-06-25", venue: "Dallas Stadium", home_code: "JPN", away_code: "SWE", home_label: "Japan", away_label: "Sweden" },
  { match_number: 58, stage: "group", group_letter: "F", date: "2026-06-25", venue: "Kansas City Stadium", home_code: "TUN", away_code: "NED", home_label: "Tunisia", away_label: "Netherlands" },
  { match_number: 59, stage: "group", group_letter: "D", date: "2026-06-25", venue: "Los Angeles Stadium", home_code: "TUR", away_code: "USA", home_label: "Türkiye", away_label: "USA" },
  { match_number: 60, stage: "group", group_letter: "D", date: "2026-06-25", venue: "San Francisco Bay Area Stadium", home_code: "PAR", away_code: "AUS", home_label: "Paraguay", away_label: "Australia" },
  { match_number: 61, stage: "group", group_letter: "I", date: "2026-06-26", venue: "Boston Stadium", home_code: "NOR", away_code: "FRA", home_label: "Norway", away_label: "France" },
  { match_number: 62, stage: "group", group_letter: "I", date: "2026-06-26", venue: "Toronto Stadium", home_code: "SEN", away_code: "IRQ", home_label: "Senegal", away_label: "Iraq" },
  { match_number: 63, stage: "group", group_letter: "G", date: "2026-06-26", venue: "Seattle Stadium", home_code: "EGY", away_code: "IRN", home_label: "Egypt", away_label: "IR Iran" },
  { match_number: 64, stage: "group", group_letter: "G", date: "2026-06-26", venue: "BC Place Vancouver", home_code: "NZL", away_code: "BEL", home_label: "New Zealand", away_label: "Belgium" },
  { match_number: 65, stage: "group", group_letter: "H", date: "2026-06-26", venue: "Houston Stadium", home_code: "CPV", away_code: "KSA", home_label: "Cabo Verde", away_label: "Saudi Arabia" },
  { match_number: 66, stage: "group", group_letter: "H", date: "2026-06-26", venue: "Estadio Guadalajara", home_code: "URU", away_code: "ESP", home_label: "Uruguay", away_label: "Spain" },
  { match_number: 67, stage: "group", group_letter: "L", date: "2026-06-27", venue: "New York New Jersey Stadium", home_code: "PAN", away_code: "ENG", home_label: "Panama", away_label: "England" },
  { match_number: 68, stage: "group", group_letter: "L", date: "2026-06-27", venue: "Philadelphia Stadium", home_code: "CRO", away_code: "GHA", home_label: "Croatia", away_label: "Ghana" },
  { match_number: 69, stage: "group", group_letter: "J", date: "2026-06-27", venue: "Kansas City Stadium", home_code: "ALG", away_code: "AUT", home_label: "Algeria", away_label: "Austria" },
  { match_number: 70, stage: "group", group_letter: "J", date: "2026-06-27", venue: "Dallas Stadium", home_code: "JOR", away_code: "ARG", home_label: "Jordan", away_label: "Argentina" },
  { match_number: 71, stage: "group", group_letter: "K", date: "2026-06-27", venue: "Miami Stadium", home_code: "COL", away_code: "POR", home_label: "Colombia", away_label: "Portugal" },
  { match_number: 72, stage: "group", group_letter: "K", date: "2026-06-27", venue: "Atlanta Stadium", home_code: "COD", away_code: "UZB", home_label: "Congo DR", away_label: "Uzbekistan" },
];

const KNOCKOUT_FIXTURES: FixtureSeed[] = [
  { match_number: 73, stage: "round_of_32", date: "2026-06-28", venue: "Los Angeles Stadium", home_label: "Group A runner-up", away_label: "Group B runner-up" },
  { match_number: 74, stage: "round_of_32", date: "2026-06-29", venue: "Boston Stadium", home_label: "Group E winner", away_label: "Third-place qualifier" },
  { match_number: 75, stage: "round_of_32", date: "2026-06-29", venue: "Estadio Monterrey", home_label: "Group F winner", away_label: "Group C runner-up" },
  { match_number: 76, stage: "round_of_32", date: "2026-06-29", venue: "Houston Stadium", home_label: "Group C winner", away_label: "Group F runner-up" },
  { match_number: 77, stage: "round_of_32", date: "2026-06-30", venue: "New York New Jersey Stadium", home_label: "Group I winner", away_label: "Third-place qualifier" },
  { match_number: 78, stage: "round_of_32", date: "2026-06-30", venue: "Dallas Stadium", home_label: "Group E runner-up", away_label: "Group I runner-up" },
  { match_number: 79, stage: "round_of_32", date: "2026-06-30", venue: "Mexico City Stadium", home_label: "Group A winner", away_label: "Third-place qualifier" },
  { match_number: 80, stage: "round_of_32", date: "2026-07-01", venue: "Atlanta Stadium", home_label: "Group L winner", away_label: "Third-place qualifier" },
  { match_number: 81, stage: "round_of_32", date: "2026-07-01", venue: "San Francisco Bay Area Stadium", home_label: "Group D winner", away_label: "Third-place qualifier" },
  { match_number: 82, stage: "round_of_32", date: "2026-07-01", venue: "Seattle Stadium", home_label: "Group G winner", away_label: "Third-place qualifier" },
  { match_number: 83, stage: "round_of_32", date: "2026-07-02", venue: "Toronto Stadium", home_label: "Group K runner-up", away_label: "Group L runner-up" },
  { match_number: 84, stage: "round_of_32", date: "2026-07-02", venue: "Los Angeles Stadium", home_label: "Group H winner", away_label: "Group J runner-up" },
  { match_number: 85, stage: "round_of_32", date: "2026-07-02", venue: "BC Place Vancouver", home_label: "Group B winner", away_label: "Third-place qualifier" },
  { match_number: 86, stage: "round_of_32", date: "2026-07-03", venue: "Miami Stadium", home_label: "Group J winner", away_label: "Group H runner-up" },
  { match_number: 87, stage: "round_of_32", date: "2026-07-03", venue: "Kansas City Stadium", home_label: "Group K winner", away_label: "Third-place qualifier" },
  { match_number: 88, stage: "round_of_32", date: "2026-07-03", venue: "Dallas Stadium", home_label: "Group D runner-up", away_label: "Group G runner-up" },
  { match_number: 89, stage: "round_of_16", date: "2026-07-04", venue: "Philadelphia Stadium", home_label: "Winner Match 74", away_label: "Winner Match 77" },
  { match_number: 90, stage: "round_of_16", date: "2026-07-04", venue: "Houston Stadium", home_label: "Winner Match 73", away_label: "Winner Match 75" },
  { match_number: 91, stage: "round_of_16", date: "2026-07-05", venue: "New York New Jersey Stadium", home_label: "Winner Match 76", away_label: "Winner Match 78" },
  { match_number: 92, stage: "round_of_16", date: "2026-07-05", venue: "Mexico City Stadium", home_label: "Winner Match 79", away_label: "Winner Match 80" },
  { match_number: 93, stage: "round_of_16", date: "2026-07-06", venue: "Dallas Stadium", home_label: "Winner Match 83", away_label: "Winner Match 84" },
  { match_number: 94, stage: "round_of_16", date: "2026-07-06", venue: "Seattle Stadium", home_label: "Winner Match 81", away_label: "Winner Match 82" },
  { match_number: 95, stage: "round_of_16", date: "2026-07-07", venue: "Atlanta Stadium", home_label: "Winner Match 86", away_label: "Winner Match 88" },
  { match_number: 96, stage: "round_of_16", date: "2026-07-07", venue: "BC Place Vancouver", home_label: "Winner Match 85", away_label: "Winner Match 87" },
  { match_number: 97, stage: "quarterfinal", date: "2026-07-09", venue: "Boston Stadium", home_label: "Winner Match 89", away_label: "Winner Match 90" },
  { match_number: 98, stage: "quarterfinal", date: "2026-07-10", venue: "Los Angeles Stadium", home_label: "Winner Match 93", away_label: "Winner Match 94" },
  { match_number: 99, stage: "quarterfinal", date: "2026-07-11", venue: "Miami Stadium", home_label: "Winner Match 91", away_label: "Winner Match 92" },
  { match_number: 100, stage: "quarterfinal", date: "2026-07-11", venue: "Kansas City Stadium", home_label: "Winner Match 95", away_label: "Winner Match 96" },
  { match_number: 101, stage: "semifinal", date: "2026-07-14", venue: "Dallas Stadium", home_label: "Winner Match 97", away_label: "Winner Match 98" },
  { match_number: 102, stage: "semifinal", date: "2026-07-15", venue: "Atlanta Stadium", home_label: "Winner Match 99", away_label: "Winner Match 100" },
  { match_number: 103, stage: "third_place", date: "2026-07-18", venue: "Miami Stadium", home_label: "Loser Match 101", away_label: "Loser Match 102" },
  { match_number: 104, stage: "final", date: "2026-07-19", venue: "New York New Jersey Stadium", home_label: "Winner Match 101", away_label: "Winner Match 102" },
];


export const ALL_FIXTURES: FixtureSeed[] = [...GROUP_FIXTURES, ...KNOCKOUT_FIXTURES];
